CREATE TABLE KHACHHANG
(
						MAKH CHAR(10) CONSTRAINT KH_PK PRIMARY KEY,
						TENKH VARCHAR(10) NOT NULL,
						DIACHI VARCHAR(50) ,
						SODT INT CONSTRAINT  DT_NN NOT NULL,
						MASOTHUE VARCHAR(10) CONSTRAINT MST_NN NOT NULL,
)

CREATE TABLE PHONG(
						MAPHONG CHAR(10) CONSTRAINT MP_PK PRIMARY KEY,
						SOKHACHTOIDA INT DEFAULT 15,
						TRANGTHAI VARCHAR (20) NULL,
						MOTA VARCHAR(20) NOT NULL,
						)
CREATE TABLE MUCTIENGIO
(
						MATIENGIO CHAR(10) CONSTRAINT MTG_PK PRIMARY KEY,
						DONGIA VARCHAR(10) NOT NULL,
						MOTA VARCHAR(40) NOT NULL,
						)
CREATE TABLE HOADON
(
						MAHD CHAR(10) CONSTRAINT MHD_PK PRIMARY KEY,
						MAKH CHAR(10) ,CONSTRAINT HD_MAHD_PK FOREIGN KEY  (MAKH)
						 REFERENCES KHACHHANG(MAKH), 
						 MAPHONG CHAR(10),CONSTRAINT HD_MAPHONG FOREIGN KEY (MAPHONG)
						 REFERENCES PHONG (MAPHONG),
						 MATIENGIO CHAR(10),
						 CONSTRAINT HD_MATIENGIO FOREIGN KEY(MATIENGIO)
						 REFERENCES MUCTIENGIO(MATIENGIO),
						 THOIGIANBDSD DECIMAL(8,0) NOT NULL,
						 THOIGIANKTSD DECIMAL(8,0) NOT NULL,
						 TRANGTHAIHD VARCHAR(10) NULL,
						)
CREATE TABLE DICHVU
(
					MADV CHAR(10) CONSTRAINT MADV_PK PRIMARY KEY,
					TENDV VARCHAR(10) NOT NULL,
					DONVITINH CHAR(10) NOT NULL,
					DONGIA INT NOT NULL,
					)
CREATE TABLE CHITET_SUDUNGDV
(
						MAHD CHAR(10) FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
						MADV CHAR(10) CONSTRAINT MADV1_PK FOREIGN KEY  (MADV)
						 REFERENCES DICHVU(MADV), 
						SOLUONG INT NOT NULL,
						)
				




